BoxLayout:
    orientation: "vertical"
    padding: 10
    spacing: 10

    BoxLayout:
        orientation: "horizontal"
        spacing: 10

        Button:
            text: "-"
            font_size: 32
            on_press: app.handle_increment(-1)

        TextInput:
            id: input_miles
            text: "0"
            font_size: 32
            multiline: False
            input_filter: "float"

        Button:
            text: "+"
            font_size: 32
            on_press: app.handle_increment(1)

    Button:
        text: "Convert"
        font_size: 24
        on_press: app.handle_convert()

    Label:
        text: f"{app.output_km} km"
        font_size: 32
        color: (1, 1, 0, 1)   # yellow
