BoxLayout:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    BoxLayout:
        orientation: 'vertical'
        id: entries_box
        spacing: 5

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        spacing: 10

        Button:
            text: "Create Widgets"
            on_press: app.create_widgets()

        Button:
            text: "Clear Widgets"
            on_press: app.clear_all()
