BoxLayout:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    BoxLayout:
        orientation: 'horizontal'
        spacing: 10

        TextInput:
            id: input_number
            text: ''
            font_size: 48
            multiline: False
        Button:
            text: 'Square'
            # the following line specifies the function in the app class to call when the button is pressed
            on_press: app.handle_calculate()
        Label:
            id: output_label
            text: '0'
            color: (1, 0, 1, 1)
            font_size: 24

    Label:
        text: 'Enter a number and press "Square"'
        font_size: 22